miSitioWeb/MiSitioWeb/Controllers/AdmPersonalProjectsController.cs
namespace MiSitioWeb.Controllers
{
    using Comun.Tool;
    using Data.Models.Crud;
    using Data.Models.Tables;
    using System.Web.Mvc;

    public class AdmPersonalProjectsController : Controller
    {
        // GET: AdmPersonalProjects
        public ActionResult Index()
        {
            string GetDataIndex = "/AdmPersonalProjects/GetDataIndex";
            string LocationCreate = "/AdmPersonalProjects/Create";
            string LocationEdit = "/AdmPersonalProjects/Edit?PersonalProjectId=";
            string LocationDelete = "/AdmPersonalProjects/Delete?PersonalProjectId=";

            ViewBag.GetDataIndex = GetDataIndex;
            ViewBag.LocationCreate = LocationCreate;
            ViewBag.LocationEdit = LocationEdit;
            ViewBag.LocationDelete = LocationDelete;

            return View();
        }

        [HttpGet]
        public JsonResult GetDataIndex()
        {
            var eLevels = DTPersonalProject.GetList();
            return Json(eLevels, JsonRequestBehavior.AllowGet);
        }

        // GET: AdmPersonalProjects/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdmPersonalProjects/Create
        [HttpPost]
        public JsonResult Create(PersonalProject model)
        {
            model.UserId = 1;
            return Json(DTPersonalProject.Create(model));
        }

        // GET: AdmPersonalProjects/Edit/5
        public ActionResult Edit(int PersonalProjectId)
        {
            ViewBag.PersonalProjectId = PersonalProjectId;
            return View();
        }

        [HttpGet]
        public JsonResult GetEditPersonalProject(int PersonalProjectId)
        {
            PersonalProject find = DTPersonalProject.Find(PersonalProjectId).To<PersonalProject>();
            return Json(find, JsonRequestBehavior.AllowGet);
        }

        // POST: AdmPersonalProjects/Edit/5
        [HttpPost]
        public ActionResult Edit(PersonalProject model)
        {
            return Json(DTPersonalProject.Create(model));
        }

        // POST: AdmPersonalProjects/Delete/5
        [HttpGet]
        public JsonResult Delete(int PersonalProjectId)
        {
            return Json(DTPersonalProject.Delete(PersonalProjectId), JsonRequestBehavior.AllowGet);
        }
    }
}

miSitioWeb/MiSitioWeb/Views/AdmPersonalProjects/Create.cshtml
@{
    ViewBag.Title = "Create Personal Project";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Crear - Proyecto Personal
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formPP" v-on:submit="createPersonalProject">
                            <div class="form-group">
                                <label for="Project">Proyecto:</label>
                                <input v-model="vModel.Project" required oninvalid="this.setCustomValidity('Escribe el nombre del proyecto')" oninput="setCustomValidity('')" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">Descripción:</label>
                                <textarea v-model="vModel.Description" required oninvalid="this.setCustomValidity('Escribe la descripción')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese una descripción del proyecto" style="height: 150px; resize: none;"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha de publicación:</label>
                                <input v-model="vModel.PublicationDate" required oninvalid="this.setCustomValidity('Escribe el nombre del proyecto')" oninput="setCustomValidity('')" type="date" class="form-control" id="PublicationDate" aria-describedby="emailHelp" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Google Play Store (Si aplica):</label>
                                <input v-model="vModel.PlayStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Apple App Store (Si aplica):</label>
                                <input v-model="vModel.AppStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Microsoft Store (Si aplica):</label>
                                <input v-model="vModel.WinStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Sitio (Si aplica):</label>
                                <input v-model="vModel.SiteURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "AdmPersonalProjects")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Models/PersonalProject/Create.js"></script>

miSitioWeb/MiSitioWeb/Views/AdmPersonalProjects/Edit.cshtml
@{
    ViewBag.Title = "Edit Personal Project";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Editar - Proyecto Personal
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formPP" v-on:submit="editPersonalProject">
                            <input type="hidden" id="PersonalProjectId" name="PersonalProjectId" value="@ViewBag.PersonalProjectId" />
                            <div class="form-group">
                                <label for="Project">Proyecto:</label>
                                <input v-model="vModel.Project" required oninvalid="this.setCustomValidity('Escribe el nombre del proyecto')" oninput="setCustomValidity('')" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">Descripción:</label>
                                <textarea v-model="vModel.Description" required oninvalid="this.setCustomValidity('Escribe la descripción')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese una descripción del proyecto" style="height: 150px; resize: none;"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha de publicación:</label>
                                <input v-model="vModel.PublicationDate" required oninvalid="this.setCustomValidity('Escribe el nombre del proyecto')" oninput="setCustomValidity('')" type="date" class="form-control" id="PublicationDate" aria-describedby="emailHelp" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Google Play Store (Si aplica):</label>
                                <input v-model="vModel.PlayStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Apple App Store (Si aplica):</label>
                                <input v-model="vModel.AppStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Microsoft Store (Si aplica):</label>
                                <input v-model="vModel.WinStoreURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <label for="Description">URL Sitio (Si aplica):</label>
                                <input v-model="vModel.SiteURL" type="text" class="form-control" id="Project" aria-describedby="emailHelp" placeholder="Ingrese el nombre del proyecto" />
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "AdmPersonalProjects")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/PersonalProject/Edit.js"></script>

miSitioWeb/MiSitioWeb/Views/AdmPersonalProjects/Index.cshtml
@{
    ViewBag.Title = "Proyecto Personal";
}

<input type="hidden" id="GetDataIndex" name="GetDataIndex" value="@ViewBag.GetDataIndex" />
<input type="hidden" id="LocationCreate" name="LocationCreate" value="@ViewBag.LocationCreate" />
<input type="hidden" id="LocationEdit" name="LocationEdit" value="@ViewBag.LocationEdit" />
<input type="hidden" id="LocationDelete" name="LocationDelete" value="@ViewBag.LocationDelete" />

<div id="MainDiv">
    <div>
        <form v-on:submit="addElement">
            <button class="btn btn-primary btn-ladda ladda-button" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-plus-square-o"></i> Agregar Proyecto Personal</span>
                <span class="ladda-spinner"></span>
            </button>
            <br />
        </form>
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Proyecto Personal
            <br />
            <div class="col-lg-4">
                <input type="text" v-model="search" placeholder="Buscar..." class="form-control" />
            </div>
        </div>
        <div>
            <grid :rows="filteredList"
                  :columna="['PersonalProjectId','Project']"
                  :filter-key="search">
            </grid>
        </div>
    </div>

    <div class="modal" id="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminar registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Se eliminara el registro seleccionado&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button v-on:click="deleteElement(itemToDelete)" type="button" class="btn btn-primary">Aceptar</button>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/GetModels.js"></script>
<script src="~/Scripts/Vrid.js"></script>