miSitioWeb/MiSitioWeb/Controllers/SocialNetworksController.cs
namespace MiSitioWeb.Controllers
{
    using Data.Models.Crud;
    using Data.Models.Tables;
    using System.Web.Mvc;

    public class SocialNetworksController : Controller
    {
        public ActionResult Index()
        {
            string GetDataIndex = "/SocialNetworks/GetDataIndex";
            string LocationCreate = "/SocialNetworks/Create";
            string LocationEdit = "/SocialNetworks/Edit?SocialNetworkId=";
            string LocationDelete = "/SocialNetworks/Delete?SocialNetworkId=";

            ViewBag.GetDataIndex = GetDataIndex;
            ViewBag.LocationCreate = LocationCreate;
            ViewBag.LocationEdit = LocationEdit;
            ViewBag.LocationDelete = LocationDelete;

            return View();
        }

        [HttpGet]
        public JsonResult GetDataIndex()
        {
            var eLevels = DTSocialNetwork.GetList();
            return Json(eLevels, JsonRequestBehavior.AllowGet);
        }

        // GET: SocialNetworks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SocialNetworks/Create
        [HttpPost]
        public JsonResult Create(SocialNetwork model)
        {
            return Json(DTSocialNetwork.Create(model));
        }

        // GET: SocialNetworks/Edit/5
        public ActionResult Edit(int SocialNetworkId)
        {
            ViewBag.SocialId = SocialNetworkId;
            return View();
        }

        [HttpGet]
        public JsonResult GetEditSocialNetwork(int SocialId)
        {
            SocialNetwork SocialNetwork = DTSocialNetwork.Find(SocialId);
            return Json(SocialNetwork, JsonRequestBehavior.AllowGet);
        }

        // POST: SocialNetworks/Edit/5
        [HttpPost]
        public ActionResult Edit(SocialNetwork model)
        {
            return Json(DTSocialNetwork.Create(model));
        }

        // POST: SocialNetworks/Delete/5
        [HttpGet]
        public JsonResult Delete(int SocialNetworkId)
        {
            return Json(DTSocialNetwork.Delete(SocialNetworkId), JsonRequestBehavior.AllowGet);
        }
    }
}

miSitioWeb/MiSitioWeb/Views/SocialNetworks/Create.cshtml
@{
    ViewBag.Title = "Create Social Network";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Crear - Red Social
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formSN" v-on:submit="createSocialNetwork">
                            <div class="form-group">
                                <label for="Description">Red Social:</label>
                                <input v-model="vModel.Description" required oninvalid="this.setCustomValidity('Escribe la red social a guardar')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la red social a guardar">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "SocialNetworks")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Models/SocialNetwork/Create.js"></script>

miSitioWeb/MiSitioWeb/Views/SocialNetworks/Edit.cshtml
@{
    ViewBag.Title = "Edit Social Network";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Editar - Red Social
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formSN" v-on:submit="editSocialNetwork">
                            <input id="SocialId" name="SocialId" hidden value="@ViewBag.SocialId" />
                            <div class="form-group">
                                <label for="Description">Red Social:</label>
                                <input v-model="vModel.Description" required oninvalid="this.setCustomValidity('Escribe la red social a guardar')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la red social a guardar">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "SocialNetworks")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/SocialNetwork/Edit.js"></script>

miSitioWeb/MiSitioWeb/Views/SocialNetworks/Index.cshtml
@{
    ViewBag.Title = "Redes Sociales";
}

<input type="hidden" id="GetDataIndex" name="GetDataIndex" value="@ViewBag.GetDataIndex" />
<input type="hidden" id="LocationCreate" name="LocationCreate" value="@ViewBag.LocationCreate" />
<input type="hidden" id="LocationEdit" name="LocationEdit" value="@ViewBag.LocationEdit" />
<input type="hidden" id="LocationDelete" name="LocationDelete" value="@ViewBag.LocationDelete" />

<div id="MainDiv">
    <div>
        <form v-on:submit="addElement">
            <button class="btn btn-primary btn-ladda ladda-button" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-plus-square-o"></i> Agregar Red Social</span>
                <span class="ladda-spinner"></span>
            </button>
            <br />
        </form>
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Redes Sociales
            <br />
            <div class="col-lg-4">
                <input type="text" v-model="search" placeholder="Buscar..." class="form-control" />
            </div>
        </div>
        <div>
            <grid :rows="filteredList"
                  :columna="['SocialId','Description']"
                  :filter-key="search">
            </grid>
        </div>
    </div>

    <div class="modal" id="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminar registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Se eliminara el registro seleccionado&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button v-on:click="deleteElement(itemToDelete)" type="button" class="btn btn-primary">Aceptar</button>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/GetModels.js"></script>
<script src="~/Scripts/Vrid.js"></script>