miSitioWeb/MiSitioWeb/Controllers/NivelesEducativosController.cs
namespace MiSitioWeb.Controllers
{
    using Data.Models.Crud;
    using Data.Models.Tables;
    using System.Web.Mvc;

    public class NivelesEducativosController : Controller
    {
        // GET: NivelesEducativos
        public ActionResult Index()
        {
            string GetDataIndex = "/NivelesEducativos/GetDataIndex";
            string LocationCreate = "/NivelesEducativos/Create";
            string LocationEdit = "/NivelesEducativos/Edit?EducationLevelId=";
            string LocationDelete = "/NivelesEducativos/Delete?EducationLevelId=";

            ViewBag.GetDataIndex = GetDataIndex;
            ViewBag.LocationCreate = LocationCreate;
            ViewBag.LocationEdit = LocationEdit;
            ViewBag.LocationDelete = LocationDelete;

            return View();
        }

        [HttpGet]
        public JsonResult GetDataIndex()
        {
            var eLevels = DTEducationLevel.GetList();
            return Json(eLevels, JsonRequestBehavior.AllowGet);
        }

        // GET: NivelesEducativos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NivelesEducativos/Create
        [HttpPost]
        public JsonResult Create(EducationLevel model)
        {
            return Json(DTEducationLevel.Create(model));
        }

        // GET: NivelesEducativos/Edit/5
        public ActionResult Edit(int EducationLevelId)
        {
            ViewBag.EducationLevelId = EducationLevelId;
            return View();
        }

        [HttpGet]
        public JsonResult GetEditEducationLevel(int EducationLevelId)
        {
            EducationLevel educationLevel = DTEducationLevel.Find(EducationLevelId);
            return Json(educationLevel, JsonRequestBehavior.AllowGet);
        }

        // POST: NivelesEducativos/Edit/5
        [HttpPost]
        public ActionResult Edit(EducationLevel model)
        {
            return Json(DTEducationLevel.Create(model));
        }

        // POST: NivelesEducativos/Delete/5
        [HttpGet]
        public JsonResult Delete(int EducationLevelId)
        {
            return Json(DTEducationLevel.Delete(EducationLevelId), JsonRequestBehavior.AllowGet);
        }
    }
}

miSitioWeb/MiSitioWeb/Views/NivelesEducativos/Create.cshtml
@{
    ViewBag.Title = "Create Education Level";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
        Nivel Educativo
    </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Crear - Nivel Educativo
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formEL" v-on:submit="createEducationLevel">
                            <div class="form-group">
                                <label for="Description">Nivel Educativo:</label>
                                <input v-model="vModel.Description" required oninvalid="this.setCustomValidity('Escribe el nivel educativo a guardar')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el Nivel Educativo a guardar">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "NivelesEducativos")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/Models/NivelEducativo/Create.js"></script>

miSitioWeb/MiSitioWeb/Views/NivelesEducativos/Edit.cshtml
@{
    ViewBag.Title = "Edit Education Level";
}

<div id="MainDiv">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Editar - Nivel Educativo
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formEL" v-on:submit="editEducationLevel">
                            <input id="EducationLevelId" name="EducationLevelId" hidden value="@ViewBag.EducationLevelId" />
                            <div class="form-group">
                                <label for="Description">Nivel Educativo:</label>
                                <input v-model="vModel.Description" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el Nivel Educativo a guardar">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Edit" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "NivelesEducativos")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/NivelEducativo/Edit.js"></script>

miSitioWeb/MiSitioWeb/Views/NivelesEducativos/Index.cshtml
@{
    ViewBag.Title = "Nivel Educativo";
}

<input type="hidden" id="GetDataIndex" name="GetDataIndex" value="@ViewBag.GetDataIndex" />
<input type="hidden" id="LocationCreate" name="LocationCreate" value="@ViewBag.LocationCreate" />

<div id="MainDiv">
    <div class="card-header">
        <i class="fa fa-align-justify"></i> Cadenas
        <br />
        <div class="col-lg-4">
            <input type="text" v-model="search" placeholder="Buscar..." class="form-control" />
        </div>
    </div>
    <div>
        <grid 
              :rows="filteredList"
              :columna="['EducationLevelId','Description']"
              :filter-key="search">
        </grid>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/GetModels.js"></script>
<script src="~/Scripts/Vrid.js"></script>