miSitioWeb/MiSitioWeb/Controllers/AdmEducationsController.cs
namespace MiSitioWeb.Controllers
{
    using Data.Models.Crud;
    using Data.Models.Tables;
    using Data.Models.DTO;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Comun.Tool;

    public class AdmEducationsController : Controller
    {
        // GET: Educations
        public ActionResult Index()
        {
            string GetDataIndex = "/AdmEducations/GetDataIndex";
            string LocationCreate = "/AdmEducations/Create";
            string LocationEdit = "/AdmEducations/Edit?EducationId=";
            string LocationDelete = "/AdmEducations/Delete?EducationId=";
            string SelectLocation = "/AdmScholarshipProjects?EducationId=";

            ViewBag.GetDataIndex = GetDataIndex;
            ViewBag.LocationCreate = LocationCreate;
            ViewBag.LocationEdit = LocationEdit;
            ViewBag.LocationDelete = LocationDelete;
            ViewBag.SelectLocation = SelectLocation;

            return View();
        }

        [HttpGet]
        public JsonResult GetDataIndex()
        {
            var eLevels = DTEducation.GetList();
            return Json(eLevels, JsonRequestBehavior.AllowGet);
        }

        // GET: Educations/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetDataEducationLevel()
        {
            List<EducationLevel> educationLevelList = DTEducationLevel.GetList();
            return Json(educationLevelList, JsonRequestBehavior.AllowGet);
        }

        // POST: Educations/Create
        [HttpPost]
        public JsonResult Create(Education model)
        {
            //User user = new User()
            //{
            //    LastName = "Luna",
            //    MiddleName = "Serrano",
            //    FirstName = "Marco Antonio",
            //    BirthDate = new System.DateTime(1992, 5, 3),
            //    UserName = "donverga",
            //    RealPassword = "123456",
            //    Email = "correo@cosmic.mx"
            //};

            //DTUser.CreateUser(user);
            model.UserId = 1;
            return Json(DTEducation.Create(model));
        }

        // GET: Educations/Edit/5
        public ActionResult Edit(int EducationId)
        {
            ViewBag.EducationId = EducationId;
            return View();
        }

        [HttpGet]
        public JsonResult GetEditEducation(int EducationId)
        {
            Education find = DTEducation.Find(EducationId).To<Education>();
            return Json(find, JsonRequestBehavior.AllowGet);
        }

        // POST: Educations/Edit/5
        [HttpPost]
        public ActionResult Edit(Education model)
        {
            return Json(DTEducation.Create(model));
        }

        // POST: Educations/Delete/5
        [HttpGet]
        public JsonResult Delete(int EducationId)
        {
            return Json(DTEducation.Delete(EducationId), JsonRequestBehavior.AllowGet);
        }
    }
}

miSitioWeb/MiSitioWeb/Views/AdmEducations/Create.cshtml
@{
    ViewBag.Title = "Create Education";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Crear - Educación
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formEducation" v-on:submit="createEducation">
                            <div class="form-group">
                                <label for="EducationLevel">Nivel Educativo:</label>
                                <select v-model="vModel.EducationLevelId" required oninvalid="this.setCustomValidity('Seleccione un nivel educativo del listado')" oninput="setCustomValidity('')" name="EducationLevelId" id="EducationLevelId" class="form-control select2-single">
                                    <option selected value="" disabled="disabled">Seleccione una opcion...</option>
                                    <option v-for="(item, index) in vEducationLevel" :value=item.EducationLevelId>
                                        {{ item.Description }}
                                    </option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="Description">Escuela:</label>
                                <input v-model="vModel.School" required oninvalid="this.setCustomValidity('Escribe el nombre de la escuela')" oninput="setCustomValidity('')" type="text" class="form-control" id="School" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la escuela">
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha de inicio:</label>
                                <input v-model="vModel.StartDate" required oninvalid="this.setCustomValidity('Escribe la fecha de ingreso')" oninput="setCustomValidity('')" type="date" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la fecha de ingreso">
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha Fin:</label>
                                <input v-model="vModel.EndDate" required oninvalid="this.setCustomValidity('Escribe la fecha de egreso')" oninput="setCustomValidity('')" type="date" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la fecha de egreso">
                            </div>
                            <div class="form-group">
                                <label for="Description">Estado:</label>
                                <input v-model="vModel.State" required oninvalid="this.setCustomValidity('Escribe el estado que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el estado que pertenece">
                            </div>
                            <div class="form-group">
                                <label for="Description">Municipio</label>
                                <input v-model="vModel.Town" required oninvalid="this.setCustomValidity('Escribe el municipio que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el municipio que pertenece">
                            </div>
                            <div class="form-group">
                                <label for="Description">País:</label>
                                <input v-model="vModel.Country" required oninvalid="this.setCustomValidity('Escribe el país que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el país que pertenece">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "AdmEducations")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/Education/Create.js"></script>

miSitioWeb/MiSitioWeb/Views/AdmEducations/Edit.cshtml
@{
    ViewBag.Title = "Edit Education";
}

<div id="MainDiv">
    @*<h4 class="jumbotron">
            Nivel Educativo
        </h4>*@
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <i class="icon-note"></i> Editar - Educación
                    <div class="card-actions">
                    </div>
                </div>
                <div class="card-body">
                    <div class="col-md-6">
                        <form id="formEducation" v-on:submit="editEducation">
                            <input id="EducationId" name="EducationId" hidden value="@ViewBag.EducationId" />
                            <div class="form-group">
                                <label for="Description">Nivel Educativo:</label>
                                <select v-model="vModel.EducationLevelId" required oninvalid="this.setCustomValidity('Seleccione un nivel educativo del listado')" oninput="setCustomValidity('')" name="EducationLevelId" id="EducationLevelId" class="form-control select2-single">
                                    <option selected value="" disabled="disabled">Seleccione una opcion...</option>
                                    <option v-for="(item, index) in vEducationLevel" :value=item.EducationLevelId>
                                        {{ item.Description }}
                                    </option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="Description">Escuela:</label>
                                <input v-model="vModel.School" required oninvalid="this.setCustomValidity('Escribe el nombre de la escuela')" oninput="setCustomValidity('')" type="text" class="form-control" id="School" aria-describedby="emailHelp" placeholder="Ingrese el nombre de la escuela">
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha de inicio:</label>
                                <input v-model="vModel.StartDate" required oninvalid="this.setCustomValidity('Escribe la fecha de ingreso')" oninput="setCustomValidity('')" type="date" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la fecha de ingreso">
                            </div>
                            <div class="form-group">
                                <label for="Description">Fecha Fin:</label>
                                <input v-model="vModel.EndDate" required oninvalid="this.setCustomValidity('Escribe la fecha de egreso')" oninput="setCustomValidity('')" type="date" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese la fecha de egreso">
                            </div>
                            <div class="form-group">
                                <label for="Description">Estado:</label>
                                <input v-model="vModel.State" required oninvalid="this.setCustomValidity('Escribe el estado que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el estado que pertenece">
                            </div>
                            <div class="form-group">
                                <label for="Description">Municipio</label>
                                <input v-model="vModel.Town" required oninvalid="this.setCustomValidity('Escribe el municipio que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el municipio que pertenece">
                            </div>
                            <div class="form-group">
                                <label for="Description">País:</label>
                                <input v-model="vModel.Country" required oninvalid="this.setCustomValidity('Escribe el país que pertenece')" oninput="setCustomValidity('')" type="text" class="form-control" id="Description" aria-describedby="emailHelp" placeholder="Ingrese el país que pertenece">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary" name="Create" value="Sign up"><i class="fa fa-save"></i> Guardar</button>
                                <a class="btn btn-danger" href="@Url.Action("Index", "AdmEducations")"><i class="fa fa-times"></i> Cancelar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/Education/Edit.js"></script>

miSitioWeb/MiSitioWeb/Views/AdmEducations/Index.cshtml
@{
    ViewBag.Title = "Educación";
}

<input type="hidden" id="GetDataIndex" name="GetDataIndex" value="@ViewBag.GetDataIndex" />
<input type="hidden" id="LocationCreate" name="LocationCreate" value="@ViewBag.LocationCreate" />
<input type="hidden" id="LocationEdit" name="LocationEdit" value="@ViewBag.LocationEdit" />
<input type="hidden" id="LocationDelete" name="LocationDelete" value="@ViewBag.LocationDelete" />
<input type="hidden" id="SelectLocation" name="SelectLocation" value="@ViewBag.SelectLocation" />

<div id="MainDiv">
    <div>
        <form v-on:submit="addElement">
            <button class="btn btn-primary btn-ladda ladda-button" data-style="zoom-in">
                <span class="ladda-label"><i class="fa fa-plus-square-o"></i> Agregar Educación</span>
                <span class="ladda-spinner"></span>
            </button>
            <br />
        </form>
        <div class="card-header">
            <i class="fa fa-align-justify"></i> Cadenas
            <br />
            <div class="col-lg-4">
                <input type="text" v-model="search" placeholder="Buscar..." class="form-control" />
            </div>
        </div>
        <div>
            <grid :rows="filteredList"
                  :columna="['EducationId','EducationLevel','School','SStartDate','SEndDate']"
                  :filter-key="search">
            </grid>
        </div>
    </div>

    <div class="modal" id="deleteModal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Eliminar registro</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Se eliminara el registro seleccionado&hellip;</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <button v-on:click="deleteElement(itemToDelete)" type="button" class="btn btn-primary">Aceptar</button>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="~/Scripts/axios.min.js"></script>
<script src="~/Scripts/Models/GetModels.js"></script>
<script src="~/Scripts/Vrid.js"></script>